# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 195e6efd0002c179752952b95b39993ae5c896405e57c4aa3dfcff360a2cf288111e98328495ae83ac1f3bbd55f550d4568c7ca49d2b618409448d76c3928974
  api_token: ed37a087ad6e87f680103acd6c6c464564929141e4dd057dd6fd531c49987d1be0943f8b

test:
  secret_key_base: da6d1fbc736d3156766112e9b6ee735862a3a83976e53c3534f78aaa5311a2f98b522e2130c4963a9b1564a0432a67af263cd703783188f18832a547a3e3d63b
  api_token: ed37a087ad6e87f680103acd6c6c464564929141e4dd057dd6fd531c49987d1be0943f8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_token: <%= ENV["SECRET_API_TOKEN"] %>
